import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider, CourseProvider, I18nProvider } from "@/context";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background-main text-sm ">
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
        >
          <I18nProvider>
            <AuthProvider>
              <CourseProvider>{children}</CourseProvider>
            </AuthProvider>
          </I18nProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
